support for subdirectories
nlewo/comin pull request #49
Opened 2024-07-03 18:25 UTC by ajgon

This PR adds support for `flake.nix` files not stored in the root of the repository.

I'm aware, that my use-case may be a little bit extra-ordinary, but I maintain one big, gitops monorepo with bunch of stuff separated in different subdirectories (i.e. k8s manifests in `k8s`, nix flakes in `nix` etc.). This PR will add support of such cases, by providing option to set up custom subdirectory, while still maintaing compatibility (as the param defaults to `"."`).

I also tested this branch on my local machine, and no issues so far.

2024-07-07 07:36 UTC, nlewo requested changes
Hello @ajgon!

I agree on the principle but i think the proposed option name could be confusing with the url of the repository (`remotes.*.url`).

What about `flakeSubdirectory` (or `flakeRelativeDirectory`)?

This is the description of this option in the Nix manual:

> dir: The subdirectory of the flake in which flake.nix is located. This parameter enables having multiple flakes in a repository or tarball. The default is the root directory of the flake.

(We could also have added this option in `remotes.*.flakeSubdirectory` but the proposed implementation looks good to me.)

2024-07-07 08:20 UTC, ajgon commented
I agree, `repo_dir` wasn't a very good name :) I renamed it to `flake_subdirectory` as suggested, which sounds way better.

Regarding adding this options to `remotes.*` - I'm not sure if this is a good idea. From what I understood from the code, multiple remotes are generally the same git repository on different locations and is/are cloned to the same directory. Meaning the directory structure remain the same (i.e. they are equivalent of `git remote add .....`), so this option there wouldn't make much sense (as it has to be the same on each)?

2024-07-07 14:28 UTC, nlewo requested changes
Thanks for the changes.

One last thing: option names should be `camelCase` in NixOS modules.
Could you rename `flake_subdirectory` to `flakeSubdirectory` in the NixOS module?

(Regarding current option names ( such as `auth_token_path`), I did some mistakes and i plan to rename them.)

2024-07-09 06:33 UTC, nlewo approved these changes

2024-07-09 06:34 UTC, nlewo commented
Thank you for your contribution.

2024-07-09 06:34 UTC, merged